import numpy as np

from tensorflow.keras.preprocessing.sequence import pad_sequences

from model import train_model

# Call the train_model function and pass tokenizer and max_sequence_length as parameters
tokenizer, max_sequence_length, scaler, model, label_encoder = train_model()

# Example texts to classify
new_texts = [
    "This is a test text.",
    "Pizza is an iconic dish loved worldwide. Its origins trace back to Naples, Italy. The classic Margherita pizza is a favorite. Pizza consists of dough, cheese, and tomato sauce. Toppings range from traditional options like pepperoni to adventurous choices like prosciutto or pineapple. Pizza is versatile and can accommodate different dietary preferences. It brings people together and creates a convivial atmosphere. Regional specialties and fusions showcase its cultural impact. Making pizza at home allows for personalization and experimentation. Pizza is a symbol of comfort, satisfaction, and culinary delight.",
    "'Curiouser and curiouser!' cried Alice. She was beginning to feel very confused and bewildered. Everything around her seemed to be getting stranger by the minute. The talking White Rabbit had led her into a topsy-turvy world, and she couldn't help but follow him down the rabbit hole. As she descended, she couldn't shake the feeling that she was about to embark on an extraordinary adventure. Little did she know just how extraordinary it would turn out to be.",
    "Laptops have become an indispensable tool in our modern society, enabling us to work, connect, and entertain ourselves with unparalleled convenience. Their portable nature, combined with powerful computing capabilities, has transformed the way we approach tasks, allowing us to be productive and creative on the go. Whether it's tackling complex work projects, attending virtual meetings, streaming multimedia content, or staying connected with loved ones, laptops have become an integral part of our daily lives, providing us with a compact and versatile computing solution that adapts to our ever-changing needs.",
    "Medicine is a vast and dynamic field dedicated to the study, diagnosis, treatment, and prevention of diseases and injuries in humans. It encompasses a wide range of disciplines, including biology, chemistry, anatomy, physiology, pharmacology, and more. With its primary goal of promoting and restoring health, medicine plays a crucial role in improving the quality of life for individuals and populations. Medical professionals, such as doctors, nurses, and specialists, are at the forefront of delivering healthcare services. They utilize their extensive knowledge, skills, and experience to assess patients, identify ailments, and develop personalized treatment plans. From routine check-ups to complex surgeries, medical professionals employ evidence-based practices and advanced technologies to provide the best possible care. In addition to clinical care, medicine encompasses various specialties that focus on specific areas of the body or particular patient populations. These specialties include cardiology, neurology, pediatrics, oncology, psychiatry, and many more. Each specialization requires specialized training and expertise to address the unique challenges and needs of patients within that field. Medicine is also closely intertwined with research and innovation. Medical researchers investigate diseases, develop new treatments and therapies, and contribute to scientific advancements that shape the future of healthcare. Through clinical trials and rigorous studies, they seek to enhance our understanding of diseases and discover new ways to prevent, diagnose, and treat them. Preventive medicine is an essential aspect of healthcare, emphasizing the importance of disease prevention and health promotion. By encouraging healthy lifestyle choices, promoting vaccination, and implementing screening programs, preventive medicine aims to reduce the burden of diseases and improve overall well-being. The field of medicine continues to evolve rapidly, with advancements in technology, precision medicine, genomics, and telemedicine, among other areas. These innovations have the potential to revolutionize healthcare delivery, enhance patient outcomes, and increase access to medical services, especially in underserved areas.",
    "Frogs are fascinating amphibians that have captivated the attention and curiosity of people around the world. These small, tailless creatures are known for their unique life cycle, diverse adaptations, and important ecological roles. Frogs belong to the order Anura, which includes over 7,000 known species. They can be found in a wide range of habitats, from tropical rainforests to arid deserts and even urban areas. Frogs have moist, permeable skin that helps them breathe and stay hydrated, making them sensitive to environmental changes and indicators of ecosystem health. One of the most remarkable features of frogs is their life cycle, which involves a metamorphosis from aquatic tadpoles to terrestrial adults. Female frogs lay eggs in water, which hatch into tadpoles with gills and a tail. As they grow, tadpoles undergo a series of transformations, developing lungs, limbs, and eventually losing their tails to become fully formed frogs. This metamorphosis is a marvel of nature, reflecting the incredible adaptability of these creatures. Frogs exhibit a wide range of sizes, colors, and patterns. From the tiny Brazilian Gold Frog, measuring less than a centimeter, to the robust and vibrant Red-eyed Tree Frog, each species has its own distinct characteristics. These adaptations often serve as a means of camouflage, helping frogs blend into their surroundings and avoid predators. The unique anatomy of frogs allows them to excel in both terrestrial and aquatic environments. They have powerful hind legs, specialized for jumping and leaping, enabling them to cover significant distances in search of food or mates. Additionally, their long, sticky tongues and keen eyesight make them efficient predators, capable of capturing insects, small invertebrates, and even other frogs. Frogs play crucial roles within ecosystems as both predators and prey. They help control insect populations, serving as natural pest controllers. Furthermore, they serve as a valuable food source for a variety of animals, including birds, snakes, and larger amphibians. Unfortunately, frogs face numerous threats and are considered one of the most endangered groups of animals on the planet. Habitat loss, pollution, climate change, and diseases, such as the chytrid fungus, have led to population declines and extinctions of many frog species. Conservation efforts focused on preserving their habitats, reducing pollution, and implementing disease management strategies are crucial for their survival. Despite the challenges they face, frogs continue to captivate our imagination and remind us of the incredible diversity and resilience of life on Earth. Their unique life cycle, adaptations, and ecological significance make them an integral part of our natural world, deserving of our attention and conservation efforts.",
    "These products are best developed by people who are male themselves and understand what other men would want. The research and development, product design, and sales and marketing departments must comprise more male employees. The main contextual variable that led to P&G’s restructuring was the changes in the target market as revealed by a study. The study was conducted by Male Grooming Trends: Profiting in 2009 and Beyond. It showed that although female consumers dominated the market for personal grooming products, the market for male consumers was quickly expanding. P&G saw an opportunity to profit from an expanding market. Therefore, redesigning was necessitated by changes in the market characteristics. Several companies have restructured to capitalize on a larger target market.",
    "The words hung in the air, a stark reminder of the brutal reality that awaited them. Every year, a boy and a girl from each district would be selected to participate in the Hunger Games, a televised fight to the death. It was a twisted form of entertainment imposed by the Capitol, a reminder of their control and the price of rebellion. Katniss Everdeen stood among the girls, her face stoic but her eyes betraying her inner turmoil. She couldn't bear the thought of her younger sister, Prim, being chosen. As Effie Trinket reached into the glass bowl, pulling out a slip of paper, the tension was palpable. Time seemed to stand still as she unfolded the paper and read the name aloud.",
    "In the enchanting land of Veridian, where mythical creatures roamed and magic danced in the air, a young sorcerer named Ethan embarked on a quest to unravel the secrets of the Forbidden Forest. With his trusted staff in hand and a spellbook tucked under his arm, he ventured into the dense, ancient woods, its towering trees whispering secrets of forgotten times. As Ethan delved deeper into the forest, he felt the mystical energy growing stronger, tingling in his fingertips. He sensed the presence of hidden enchantments and elusive creatures lurking in the shadows. Each step brought him closer to the heart of the forest, where legends spoke of a magical artifact said to grant unimaginable powers.",
    "There are several arguments that can be made against the widespread automation of tasks and processes: Job displacement: One major concern about automation is that it can lead to job displacement, as machines and computer programs can often perform tasks more efficiently than human workers. This can result in widespread unemployment and economic insecurity, and can have a particularly negative impact on workers in lower-skilled and lower-paid positions. Loss of human skills and knowledge: Automation can also lead to the loss of valuable human skills and knowledge, as machines and computer programs do not have the same ability to learn and adapt as humans do. This can result in a decline in the overall quality and creativity of work, and can make it more difficult for people to adapt to new situations or challenges. Ethical concerns: There are also ethical concerns surrounding the automation of certain tasks and processes. For example, automation can sometimes lead to a lack of accountability, as it can be difficult to determine who is responsible for mistakes or failures. Automation can also raise issues of fairness and equity, as it may disproportionately benefit certain groups or individuals while disadvantaging others. Dependence on technology: Relying heavily on automation can also create a dependence on technology, which can make it more difficult to adapt when technological systems fail or are disrupted. This can create vulnerabilities and expose societies to risks that they might otherwise be able to mitigate or avoid. Overall, while automation can bring some benefits in terms of efficiency and productivity, it is important to carefully consider the potential consequences and to ensure that the benefits are distributed fairly and equitably.",
    "The weather, ever-changing and awe-inspiring, has the power to shape our daily lives and influence the world around us. It is a fascinating phenomenon that encompasses a myriad of atmospheric conditions, from clear blue skies to dramatic storms, and everything in between. The warmth of the sun's rays on a bright summer day brings a sense of joy and vitality. The gentle breeze whispers through the air, carrying the delicate fragrance of blooming flowers. It invites us to venture outdoors, to bask in the beauty of nature and engage in leisurely activities under its benevolent embrace. As autumn unfolds, the weather takes on a different character. The air becomes crisper, tinged with the earthy scent of fallen leaves. The trees transform into a splendid tapestry of red, orange, and gold, painting the landscape with their vibrant hues. Cool winds sweep through, rustling the foliage and prompting us to reach for cozy sweaters and warm beverages. Winter arrives with a touch of enchantment. Soft, glistening snowflakes descend from the sky, turning the world into a winter wonderland. The cold air invigorates, and the sound of crunching snow underfoot adds a magical rhythm to our steps. The charm of the season invites us to indulge in winter sports, build snowmen, and seek solace by a crackling fire.",
    "The percentage of Americans without health insurance also rose, though much less dramatically, to 8.6 percent in the third quarter of 2015, from 8.2 percent in the second quarter of this year. The increase was concentrated in some Southern states, including Alabama, Georgia, Kentucky, and Oklahoma. More than one in 10 households in these states, or 10.2 percent, lacked health insurance coverage. In addition, the health insurance market continued to grow more unstable, with several large companies discontinuing their health insurance plans. A fourth interesting element of this report was the finding that the share of Americans getting affordable private health insurance has fallen in recent years. In 2003, 57.7 percent of the U.S. adult population lacked health insurance during the quarter. In other words, nearly a quarter of U.S. residents were without health insurance in the third quarter, a slight improvement from 22.6 percent in the second quarter."
]

# Tokenize and convert new texts to sequences
new_sequences = tokenizer.texts_to_sequences(new_texts)
new_data = pad_sequences(new_sequences, maxlen=max_sequence_length)

# Calculate sentence lengths for new texts
new_sentence_lengths = np.array([len(text.split()) for text in new_texts])
new_sentence_lengths = scaler.transform(new_sentence_lengths.reshape(-1, 1))

# Make predictions on new data
predictions = model.predict([new_data, new_sentence_lengths])

# Decode the predictions
predicted_labels = label_encoder.inverse_transform(predictions.flatten().round().astype(int))

# Print the predictions
for text, label in zip(new_texts, predicted_labels):
    print(f"Text: {text}")
    print(f"Predicted Label: {label}")
    print()
